Added functionalities to create policy and role
coffr/poc pull request #13
Opened 2022-11-23 14:07 UTC by yerdreic

- Added 2 files under the assets dir, which are the policy and iam role json files
- Added the functionality or the creation of the policy and role
- Added the role to instance profile

2022-11-23 14:16 UTC, lmilbaum commented
Was the script validated by running it?

2022-11-23 14:16 UTC, lmilbaum requested changes

2022-11-23 14:16 UTC, lmilbaum commented on ec2_instances/assets/policy.json
> +}
Please add end of line

2022-11-23 14:16 UTC, lmilbaum commented on ec2_instances/config.sh
> +IMAGE_ID="ami-0caef02b518350c8b"
Is this change related to the PR scope?

2022-11-23 14:16 UTC, lmilbaum commented on ec2_instances/create_ec2.sh
> +if [[ "$IS_SG_EXIST" == $SG_NAME ]]; then
Is this change related to PR scope?

2022-11-23 14:16 UTC, lmilbaum commented on ec2_instances/create_ec2.sh
> +--image-id $IMAGE_ID \
same question as above

2022-11-23 20:31 UTC, yerdreic commented on ec2_instances/config.sh
> +IMAGE_ID="ami-0caef02b518350c8b"
Nope. I used this PR to fix some other syntaxes changes. Probably not the best practice. Will separate it

2022-11-24 09:25 UTC, lmilbaum approved these changes
LGTM

2022-11-24 09:26 UTC, merged