Draft: use ansible to create security group
coffr/poc pull request #33
Opened 2022-11-27 11:35 UTC by yerdreic

2022-11-27 12:01 UTC, lmilbaum commented
I am aware that this is a draft PR. Just in case, please add to the README the instructions.

2022-11-27 12:05 UTC, lmilbaum commented
And, please add a play for removing the resources

2022-11-27 12:06 UTC, lmilbaum requested changes

2022-11-27 12:06 UTC, lmilbaum commented on ansible/ec2_config.yml
> +# - name: "Set variables"
Remove the comments. Your decision to go with a vars file is the preferred one.

2022-11-27 12:06 UTC, lmilbaum commented on ansible/ec2_config.yml
> +        profile: "{{ aws_profile }}"
What is this key for?

2022-11-27 12:06 UTC, lmilbaum commented on ansible/ec2_config.yml
> +      amazon.aws.ec2_group:
The module name should be: `amazon.aws.ec2_security_group`

2022-11-27 12:06 UTC, lmilbaum commented on ansible/ec2_config.yml
> +        region: "{{ aws_region }}"
vpc_id is missing

2022-11-28 08:53 UTC, closed without merging

2022-11-28 08:54 UTC, yerdreic commented
Not relevant anymore